# Generated by Django 3.2.9 on 2021-11-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('manufacturer', models.CharField(max_length=50)),
            ],
        ),
    ]
