# Generated by Django 3.2.9 on 2021-11-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='release_date',
            new_name='available_from',
        ),
    ]
