# Generated by Django 3.2.9 on 2021-11-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_release_date_car_available_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
